trigger:
  batch: true
  branches:
    include:
      - master

pr:
  - master

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/DTSPO-15698-add-tf-test-support
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentImage
    value: ubuntu-20.04
  - name: product
    value: sds-platform
  - name: terraformInitSubscription
    value: bf308a5c-0624-4334-8ff8-8dca9fd43783
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job:
        pool: 
          vmImage: ${{ variables.agentImage }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'azurerm-sandbox'
              overrideAction: 'plan'

  - stage: Test
    dependsOn: Precheck
    jobs:
      - job: TerraformTest
        pool: 
          vmImage: ${{ variables.agentImage }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        workspace:
          clean: all
        variables:
          ARM_TENANT_ID: $(ado-sp-tenant-id)
          ARM_CLIENT_ID: $(ado-sp-id)
          ARM_CLIENT_SECRET: $(ado-sp-secret)
        steps:
          - task: AzureKeyVault@2
            displayName: Read variables from keyvault
            inputs:
              ConnectedServiceName: azurerm-sandbox
              KeyVaultName: infra-vault-nonprod
              SecretsFilter: 'ado-sp-*'
              RunAsPreJob: false
          - script: |
              az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
              az account set -s ${{ variables.azureSubscription }}
              terraform init
              terraform test
            displayName: Terraform Test