trigger:
  batch: true
  branches:
    include:
      - master

pr:
  - master

resources:
  repositories:
    - repository: cnp-azuredevops-libraries
      type: github
      ref: refs/heads/DTSPO-15698-add-tf-test-support
      name: hmcts/cnp-azuredevops-libraries
      endpoint: 'hmcts'

variables:
  - name: timeoutInMinutes
    value: 60
  - name: agentImage
    value: ubuntu-20.04
  - name: product
    value: sds-platform
  - name: terraformInitSubscription
    value: 04d27a32-7a07-48b3-95b8-3c8691e1a263
  - template: vars/input-variables.yaml@cnp-azuredevops-libraries

stages:
  - stage: Precheck
    jobs:
      - job:
        pool: 
          vmImage: ${{ variables.agentImage }}
        steps:
          - template: steps/terraform-precheck.yaml@cnp-azuredevops-libraries
            parameters:
              keyvaultName: 'infra-vault-nonprod'
              keyvaultSecret: 'azure-devops-sp-token'
              serviceConnection: 'azurerm-sandbox'
              overrideAction: 'plan'

  # - stage: Test
  #   dependsOn: Precheck
  #   jobs:
  #     - job: TerraformTest
  #       pool: 
  #         vmImage: ${{ variables.agentImage }}
  #       timeoutInMinutes: ${{ variables.timeoutInMinutes }}
  #       variables:
  #         - group: jumpbox-aad-creds
  #       steps:
  #         - template: steps/terraform-test.yaml@cnp-azuredevops-libraries
  #           parameters:
  #             environment: sandbox
  #             component: test
  #             serviceConnection: 'azurerm-sandbox'
  #             terraformInitSubscription: ${{ variables.terraformInitSubscription }}
  #             product: ${{ variables.product }}
  #             testCommandOptions: "-verbose"

  - stage: Test
    dependsOn: Precheck
    jobs:
      - job: TerraformTest
        pool: 
          vmImage: ${{ variables.agentImage }}
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        variables:
          - group: jumpbox-aad-creds
        steps:
          - task: CmdLine@2
            displayName: "Terraform Test"
            inputs:
              targetType: 'inline'
              script: |
                az login --service-principal -u $(ARM_CLIENT_ID) -t $(ARM_TENANT_ID) --password $(ARM_CLIENT_SECRET)
                terraform test